# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file
[tool.black]
target-version = ['py38']
# How to use `extend-exclude` is very poorly documented,
# but these links might be useful to understand it.
# https://github.com/psf/black/issues/1473
# https://stackoverflow.com/questions/60381208/ignoring-django-migrations-in-pyproject-toml-file-for-black-formatter
extend-exclude = '''
/(
  | migrations
)/
'''
