# Generated by Django 4.2.6 on 2023-10-23 22:30

from django.db import migrations, models
import django.db.models.deletion
import django_modern_user.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_modern_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreUser",
            fields=[
                (
                    "modernuser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_modern_user.modernuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("django_modern_user.modernuser",),
            managers=[
                ("objects", django_modern_user.models.ModernUserManager()),
            ],
        ),
    ]
