# Generated by Django 3.1.5 on 2021-01-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
