# Generated by Django 3.1.5 on 2021-01-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210110_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
