# Generated by Django 3.1.5 on 2021-01-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210112_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
    ]
