# Generated by Django 3.1.3 on 2020-11-19 18:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('biography', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('web_site_url', models.URLField(blank=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('wiki_url', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='art/piece_images/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='art.artist')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='art.location')),
                ('styles', models.ManyToManyField(blank=True, to='art.Style')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
