# Generated by Django 3.2.9 on 2021-11-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='image_b64_thumbnail',
            field=models.TextField(null=True),
        ),
    ]
