# Generated by Django 4.1.5 on 2023-01-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_piece_image_b64_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='image_b64_thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
